### ISSUE TITLE
Use CSF3 and following best practices for TypeScript stories

### ISSUE THREAD

**Issue by Robbert** [Amsterdam/design-system#144]
Recently two articles came out showing how to use Common Story Format version 3 (CSF3) and how to optimize stories for TypeScript.

- [Improved type safety in Storybook 7](https://storybook.js.org/blog/improved-type-safety-in-storybook-7/)
- [Component Story Format 3 is here](https://storybook.js.org/blog/storybook-csf3-is-here/)

Currently there are only 10 files with stories, so now seems like a great moment to upgrade to Storybook 7 convert these to the latest format so all new stories will be using the latest and greatest notation.

**Comment by VincentSmedinga** [comment]
Thanks for the heads-up, we’re on it 👍🏼

**Comment by dlnr** [comment]
Able to upgrade storybook-react but storybook-css is a challenge, there are still some webpack dependancies in babel-, style-, sass- and css-loader that I have to look into. Probably obsolete since Vite brings its own sass compiler.
