### ISSUE TITLE
Closing a Dialog with the default "x" icon triggers onSubmit()

### ISSUE THREAD

**Issue by joeyamst** [Amsterdam/design-system#1546]
# Describe the issue

When closing a `Dialog` with the default "x" icon, the `onSubmit()` hook that is given as prop to the `Dialog` will trigger. This is unwanted because the form in my dialog gets submitted without the user wanting to submit it.

## Summary

The Dialog component contains a `<form>`. When I create a Dialog and give it a `onSubmit()` prop, this function will be triggered when I press the "x" icon.

## Steps to reproduce

(Provide a clear and concise list of steps to reproduce the issue.)

1. Create a Dialog that can be opened with a button
2. Give the dialog a prop `onSubmit()` with some logging code
3. Close the dialog with the standard provided "x" icon.
4. Observe that the `onSubmit()` function is triggered

Here's a link to a codesandbox: https://codesandbox.io/p/devbox/muddy-forest-n9h9lt?workspaceId=5bdd83a2-36b4-4d1b-acb9-544b42f5ece6

## Environment

- Browser: Chrome and Firefox
- Operating System: Windows
- Version of the design system: v0.11.0

## Checklist

Before submitting your issue, please ensure you have done the following:

- [x] Search the issue tracker to ensure the issue has not already been reported.
- [x] Verify that the issue can be consistently reproduced.
- [x] Check if the issue is already documented.

## Additional notes

It is probably due to how `<form method="dialog">` handles the closing of a dialog, seeing it as a submit.

**Comment by VincentSmedinga** [comment]
Hi @joeyamst, thanks for reporting. That certainly looks like a bug. We will look into it and report back. The link to the CodeSandbox leads to a 404 for me, but we can probably reproduce without it.

**Comment by VincentSmedinga** [comment]
@joeyamst Me neither – I registered with GitHub and added additional authorization scopes, but I’m unfamiliar with that site. No worries.

We’re well underway with a solution in the PR mentioned above. I’ve just invited you to add your feedback, if any.

**Comment by VincentSmedinga** [comment]
@joeyamst We’ve just released [@amsterdam/design-system-react v0.11.1](https://github.com/Amsterdam/design-system/releases/tag/design-system-react-v0.11.1) to address this. The close button now calls the dialog’s `close` method instead of submitting its form. We also offer new `openDialog` and `closeDialog` functions.

No changes on your side are necessary. Please let us know whether this indeed resolves the problem.

**Comment by dlnr** [comment]
@joeyamst & @VincentSmedinga  The `OnSubmit` (which is a React Event handler for `<form>`) is not how a dialog is [intended](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue) to be used, the element gives you a `returnValue` (string) on submit and the `formnovalidate` attribute on the close button is to bypass the form validation, `close()` does the same thing but allows you to change the `returnValue` like `close("cancel")`.

I don't think this is a bug. You code example shows you want to do something on submit and then close it, this is what a dialog is already designed to do, it closes after a submit and the `returnvalue` allows you to determine if the form has validated and you can do something with the form. It's not very clear how to do this in react I admit. I've tried to create an [example](https://codesandbox.io/p/sandbox/dialog-test-jn722d?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0jzu1cz00063b6wxt4rey69%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0jzu1cz00023b6wly842azw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0jzu1cz00033b6w56e76i69%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0jzu1cz00053b6whrbw6uva%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0jzu1cz00023b6wly842azw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0jzu1cz00013b6wa29d1bdh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0k14zwf00023b6wmzc6yewq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0jzu1cz00023b6wly842azw%2522%252C%2522activeTabId%2522%253A%2522cm0k14zwf00023b6wmzc6yewq%2522%257D%252C%2522cm0jzu1cz00053b6whrbw6uva%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0jzu1cz00043b6wvy6sif8e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0jzu1cz00053b6whrbw6uva%2522%252C%2522activeTabId%2522%253A%2522cm0jzu1cz00043b6wvy6sif8e%2522%257D%252C%2522cm0jzu1cz00033b6w56e76i69%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0jzu1cz00033b6w56e76i69%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D).

Are you trying to add a more complicated form to the Dialog?

**Comment by joeyamst** [comment]
@VincentSmedinga After upgrading to 0.11.1 I can confirm the onSubmit() does not get triggered on closing the dialog. Thanks for the quick response!
