### ISSUE TITLE
Is it possible to remove the default padding-left in a grid?

### ISSUE THREAD

**Issue by remyvdwereld** [Amsterdam/design-system#1734]
# Describe the issue

When using a Grid, there is a default padding-left. Is it possible to remove this or create a property for this? 

Now I have to add an extra style={{ paddingLeft: 0 }}.

[Sandbox](https://codesandbox.io/p/sandbox/fileinput-grid-szrwns)

**Comment by VincentSmedinga** [comment]
I’m afraid not. The Grid is intended for page-wide layout only, and its horizontal whitespace is essential to prevent content from touching the edge of the window. What’s the reason to remove this white space?

Have you seen [our example form](https://designsystem.amsterdam/?path=/story/pages-amsterdam-nl-form-page--default)? Can you set up your form just like it?

**Comment by remyvdwereld** [comment]
I have a default layout for my pages with a padding-left. I use the Grid with a form so that means another padding-left.

**Comment by VincentSmedinga** [comment]
@remyvdwereld  It sounds like you’re nesting two Grids, but that is incorrect. The intended hierarchy is `Screen` > `Grid` > `Grid Cell` > `form` > various of `Field` and `FieldSet`.

We have yet to formulate our advice on sizing and arranging form elements. Until then, your best option is to use Screen and Grid in your default layout and create a custom grid for the fields in your form.

**Comment by VincentSmedinga** [comment]
@remyvdwereld I understand @dnlr helped you out with this yesterday. Can we close this ticket?
